<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo $this->pageTitle; ?></title>
<link href="assets/css/style.css" type="text/css" rel="stylesheet" />
</head>
<header>
    <div class="header">
        <div class="header-body">
            <div class="book-title">
                <a href="index.html"><?php echo $this->bookTitle; ?></a>
            </div>
            <div class="menu">
                <div class="link">
                    <a href="#">Read</a>
                </div>
                <div class="link">
                    <a href="#">Source</a>
                </div>
                <div class="link">
                    <a href="#">Contribute</a>
                </div>
            </div>
        </div>    
    </div>
</header>    
<body>
<div id="container">
<h1>Table of Contents</h1>
<?php echo $this->content; ?>        
</div>
<footer>
    <div class="footer">
        <div class="footer-body">
            <div class="generated-by">
                Generated by <a href="http://github.com">OpenBook</a> on <?php echo date('Y-m-d H:i') ?>
            </div>
        </div>    
    </div>
</footer>
</body>
</html>    